### ISSUE TITLE
Component disappearing after page reload

### ISSUE THREAD

**Issue by roberttolton** [JibbyJames/data-studio-lighthouse-gauge#17] opened 2022-06-07 14:53 UTC
Hi, thanks for your work on this component.

I'm experiencing an issue where the component is completely blank after reloading the page. Changing none of the styling or data options gets it to come back.

I can copy and paste the component, and sometimes the copied one will work until the next page reload. I can reproduce this by adding a fresh lighthouse component to the page, editing it a bit, reloading, and it will be broken.

It seems like some of the example gauges are having the same issue?
https://datastudio.google.com/reporting/bf0d5276-af97-4c9f-8bbe-068edbf79cbd/page/3FnaB

**Comment by roberttolton** [comment] 2022-06-07 15:26
Hi James,

I'm using Chrome for macOS 11.6.3, Version 101.0.4951.64 (Official Build) (x86_64)
I'm logged into the Google Account on Chrome (the same one that has access to the data).

There's no errors in the console log.

This is what the examples page looks like to me: https://cloud.roberttolton.com/5zurJXJq

**Comment by DigantaGhosh96-hub** [comment] 2022-06-19 05:17
I have also faced this issue, and I'm attaching an error log that I found in the Chrome Console window.
<img width="324" alt="lighthouse_error_log" src="https://user-images.githubusercontent.com/82209313/174467012-170b85d4-ef7d-4ff2-a6a2-1c5dc3518c7d.png">

I'm currently using 6 Lighthouse charts in a particular page of the report.

**Comment by JibbyJames** [comment] 2022-06-19 06:33
Hi,

Thanks for providing the error logs.

Are you also using a Mac? Haven't managed to get my hands on one yet for
testing.

Thanks,
James

**Comment by DigantaGhosh96-hub** [comment] 2022-06-19 06:45
I'm on a Windows 11 machine, currently. Haven't tried it out on a Mac yet.

**Comment by jidanzenadin** [comment] 2022-08-10 13:00
Hi, currently I'm also experiencing the same issue where the chart is disappearing when we reopen the dashboard (picture 1). However when I copy paste the chart is appears (picture 2). I'm using Chrome and Windows 11 Pro, version 21H2, x64-based processor. 

Hopefully you can fix this issue as soon as possible, thank you.

<img width="163" alt="image" src="https://user-images.githubusercontent.com/59505829/183906121-dac90c9e-b0db-4234-aa56-2bd0f0c1eb54.png">
<img width="153" alt="image" src="https://user-images.githubusercontent.com/59505829/183906217-eee7bcd0-994a-4a38-969e-56b7e8874add.png">

**Comment by JibbyJames** [comment] 2022-08-10 13:11
Hi there, thanks for letting me know.

This has been a tough one to debug because I haven't been able to reproduce
it myself yet.

**Comment by JibbyJames** [comment] 2022-11-09 22:17
No one seems to have encountered this issue in a while, and I've still been unable to reproduce it, so I'll be closing it now. Based on some of the other issues experienced in the past, I think it's related to when new Chrome versions are available, and goes away after a short while by itself.

**Closed by JibbyJames** 2022-11-09 22:17 UTC
