### ISSUE TITLE
Community visualization JavaScript error

### ISSUE THREAD

**Issue by DrNeumi** [JibbyJames/data-studio-lighthouse-gauge#10] opened 2021-02-08 14:58 UTC
Hey,

since today I see an error in Data Studio instead of the chart.
"Data Studio has encountered a system error.
Community visualization JavaScript error"

I have reviewed the changes from yesterday and I see that line one from file lhGauge.js is incomplete.

BR Denny

![Screenshot 2021-02-08 155735](https://user-images.githubusercontent.com/78743280/107236868-6920f080-6a26-11eb-9c66-c81cf40be8d5.png)

**Comment by JibbyJames** [comment] 2021-02-08 15:47
Hi BR Denny,

Line one from lhGauge is the minified DSCC library which I copied from here: 

https://raw.githubusercontent.com/googledatastudio/tooling/master/packages/ds-component/_bundles/dscc.min.js

Were there any errors in the console?

James

**Comment by DrNeumi** [comment] 2021-02-08 16:42
Hey James,

I understand, there is no error in line one. The comments and line breaks a little confusion.

In the console:
`getThirdPartyScript:22 Uncaught TypeError: Cannot read property 'forEach' of undefined`
    `at VM116 getThirdPartyScript:22`
    `at Array.forEach (<anonymous>)`
    `at a (VM116 getThirdPartyScript:22)`
    `at Object.N.objectTransform [as transform] (VM116 getThirdPartyScript:22)`
    `at e (VM116 getThirdPartyScript:22)`

Is that helpful?

Best Denny

**Comment by JibbyJames** [comment] 2021-02-08 17:19
Thanks Denny,

That was helpful, as it looks like the same error I was getting on the older library before I had to modify it myself. It is related to metrics being optional in the visualisation, as it is failing on finding a "value" in the forEach block for them. I don't know why I wasn't seen this error myself when testing again, but I assumed it had been fixed in the latest library. 

I've added the small change I made to resolve this issue back again, let me know if that has fixed it for you.

Thanks,
James

P.S.: Didn't realise "BR" was "best regards", thought it was your initials or something hahaha

**Comment by QuangTrungNguyen** [comment] 2021-02-08 18:55
Hi James,

I checked on my dashboard just now and I'm seeing the same error as well. 

Cheers,
Vincent

**Comment by JibbyJames** [comment] 2021-02-08 19:15
I've set the devmode to true just to make sure you aren't seeing a cached version still. If the error persists I'll just revert back to the previous DSCC library.

I can't reproduce this annoyingly.

**Comment by QuangTrungNguyen** [comment] 2021-02-08 19:19
Just checked and the issue has now been resolved. Thank you for fixing it!

**Comment by JibbyJames** [comment] 2021-02-08 19:22
Thanks Vincent! Will leave the dev mode on for a little while longer. I should look into addressing that issue on the DSCC repo at some point...

**Comment by JibbyJames** [comment] 2021-02-10 10:41
@DrNeumi Assuming you and Vincent were seeing the same issue, so I'm going to close this one now. Thanks for first raising it.

**Closed by JibbyJames** 2021-02-10 10:41 UTC

**Comment by DrNeumi** [comment] 2021-02-10 16:54
Hey James,

it looks good to me! Thanks for the quick support.

Best Denny
