### ISSUE TITLE
Community Visualizations Disabled

### ISSUE THREAD

**Issue by paulzny** [JibbyJames/data-studio-lighthouse-gauge#2] opened 2020-08-04 22:06 UTC
When attempting to add the gauge to my report I receive message that community visualization has been disabled. 
<img width="298" alt="Screen Shot 2020-08-04 at 6 06 37 PM" src="https://user-images.githubusercontent.com/20229664/89350037-3fed6500-d67d-11ea-8de9-c5ad1bb92376.png">

**Comment by paulzny** [comment] 2020-08-04 22:13
Nevermind.  I am an idiot.

**Comment by paulzny** [comment] 2020-08-04 22:26
I don't have the moronic error above, but I have a no gauge now that I am feeding data.  😢 

<img width="348" alt="Screen Shot 2020-08-04 at 6 24 18 PM" src="https://user-images.githubusercontent.com/20229664/89351409-f05c6880-d67f-11ea-92be-0fc969147909.png">

**Comment by JibbyJames** [comment] 2020-08-04 22:35
Glad you resolved that first issue :)

Are you seeing any errors in the browser console? Does the chart work for other data sources?

I'm planning on picking up the other open issue this week as I've been unable to recently. If this requires any code changes I can look into that as well.

**Comment by paulzny** [comment] 2020-08-04 22:51
Here are the messages in the console.  No error, 5 warning, but it doesn't look like anything related to the gauge. 

<img width="1120" alt="Screen Shot 2020-08-04 at 6 40 34 PM" src="https://user-images.githubusercontent.com/20229664/89352392-ff441a80-d681-11ea-887b-ba7329ce3454.png">

I've tried a couple different data sources, and it's just blank.  

<img width="958" alt="Screen Shot 2020-08-04 at 6 49 25 PM" src="https://user-images.githubusercontent.com/20229664/89352911-4383ea80-d683-11ea-889e-e8c9a6c57438.png">

<img width="896" alt="Screen Shot 2020-08-04 at 6 49 34 PM" src="https://user-images.githubusercontent.com/20229664/89352916-48489e80-d683-11ea-8f7e-912cc5d05865.png">

**Comment by JibbyJames** [comment] 2020-08-04 23:14
Struggling to reproduce this. Have you tried using other browsers? Are you able to get other community visualisations to work?

**Comment by paulzny** [comment] 2020-08-04 23:52
Hmm, I created a new report and it works like a champ.  I will play around with it and see what I can find.  I'll keep you posted.  Love the gauge.  It's great.

**Comment by JibbyJames** [comment] 2020-08-04 23:58
Okay, that's strange. Cool, let me know how you get on then. Thanks for the feedback :)

**Comment by JibbyJames** [comment] 2020-08-09 16:35
Have you encountered any further issues? I added some new style options today, and while I was developing/testing didn't encounter any issues like you first described.

**Comment by JibbyJames** [comment] 2020-09-27 18:42
Closing this issue now as it looks like you haven't encountered any related issues in a while.

**Closed by JibbyJames** 2020-09-27 18:42 UTC
